export default function Bd() {
  return [
    {
      idmovie: 1,
      nombre: "dc_green",
      votos: 0,
      votosN: 0,
      superhero: "Green Lantern",
      publisher: "DC Comics",
      alter_ego: "Alan Scott",
      first_appearance: "All_American Comics #16",
      characters:
        "Alan Scott, Hal Jordan, Guy Gardner, John Stewart, Kyle Raynor, Jade, Sinestro, Simon Baz",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 2,
      nombre: "dc_flash",
      votos: 0,
      votosN: 0,
      superhero: "Flash",
      publisher: "DC Comics",
      alter_ego: "Jay Garrick",
      first_appearance: "Flash Comics #1",
      characters: "Jay Garrick, Barry Allen, Wally West, Bart Allen",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 3,
      nombre: "dc_superman",
      votos: 0,
      votosN: 0,
      superhero: "Superman",
      publisher: "DC Comics",
      alter_ego: "Kal_El",
      first_appearance: "Action Comics #1",
      characters: "Kal_El",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 4,
      nombre: "dc_wonder",
      votos: 0,
      votosN: 0,
      superhero: "Wonder Woman",
      publisher: "DC Comics",
      alter_ego: "Princess Diana",
      first_appearance: "All Star Comics #8",
      characters: "Princess Diana",
      voto: 0,
      votoN: 0,
    },

    {
      idmovie: 5,
      nombre: "dc_batman",
      votos: 0,
      votosN: 0,
      superhero: "Batman",
      publisher: "DC Comics",
      alter_ego: "Bruce Wayne",
      first_appearance: "Detective Comics #27",
      characters: "Bruce Wayne",
      voto: 0,
      votoN: 0,
    },

    {
      idmovie: 6,
      nombre: "dc_arrow",
      votos: 0,
      votosN: 0,
      superhero: "Green Arrow",
      publisher: "DC Comics",
      alter_ego: "Oliver Queen",
      first_appearance: "More Fun Comics #73",
      characters: "Oliver Queen",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 7,
      nombre: "marvel_spider",
      votos: 0,
      votosN: 0,
      superhero: "Spnombreer Man",
      publisher: "Marvel Comics",
      alter_ego: "Peter Parker",
      first_appearance: "Amazing Fantasy #15",
      characters: "Peter Parker",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 8,
      nombre: "marvel_captain",
      votos: 0,
      votosN: 0,
      superhero: "Captain America",
      publisher: "Marvel Comics",
      alter_ego: "Steve Rogers",
      first_appearance: "Captain America Comics #1",
      characters: "Steve Rogers",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 9,
      nombre: "dc_martian",
      votos: 0,
      votosN: 0,
      superhero: "Martian Manhunter",
      publisher: "DC Comics",
      alter_ego: "J'onn J'onzz",
      first_appearance: "Detective Comics #225",
      characters: "Martian Manhunter",
      voto: 0,
      votoN: 0,
    },

    {
      idmovie: 10,
      nombre: "marvel_thor",
      votos: 0,
      votosN: 0,
      superhero: "Thor",
      publisher: "Marvel Comics",
      alter_ego: "Thor Odinson",
      first_appearance: "Journey into Myster #83",
      characters: "Thor Odinson",
      voto: 0,
      votoN: 0,
    },

    {
      idmovie: 11,
      nombre: "dc_robin",
      votos: 0,
      votosN: 0,
      superhero: "Robin/Nightwing",
      publisher: "DC Comics",
      alter_ego: "Dick Grayson",
      first_appearance: "Detective Comics #38",
      characters: "Dick Grayson",
      voto: 0,
      votoN: 0,
    },

    {
      idmovie: 12,
      nombre: "marvel_iron",
      votos: 0,
      votosN: 0,
      superhero: "Iron Man",
      publisher: "Marvel Comics",
      alter_ego: "Tony Stark",
      first_appearance: "Tales of Suspense #39",
      characters: "Tony Stark",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 13,
      nombre: "dc_blue",
      votos: 0,
      votosN: 0,
      superhero: "Blue Beetle",
      publisher: "DC Comics",
      alter_ego: "Dan Garret",
      first_appearance: "Mystery Men Comics #1",
      characters: "Dan Garret, Ted Kord, Jaime Reyes",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 14,
      nombre: "marvel_hulk",
      votos: 0,
      votosN: 0,
      superhero: "Hulk",
      publisher: "Marvel Comics",
      alter_ego: "Bruce Banner",
      first_appearance: "The Incredible Hulk #1",
      characters: "Bruce Banner",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 15,
      nombre: "marvel_wolverine",
      votos: 0,
      votosN: 0,
      superhero: "Wolverine",
      publisher: "Marvel Comics",
      alter_ego: "James Howlett",
      first_appearance: "The Incredible Hulk #180",
      characters: "James Howlett",
      voto: 0,
      votoN: 0,
    },

    {
      idmovie: 16,
      nombre: "marvel_daredevil",
      votos: 0,
      votosN: 0,
      superhero: "Daredevil",
      publisher: "Marvel Comics",
      alter_ego: "Matthew Michael Murdock",
      first_appearance: "Daredevil #1",
      characters: "Matthew Michael Murdock",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 17,
      nombre: "marvel_cyclops",
      votos: 0,
      votosN: 0,
      superhero: "Cyclops",
      publisher: "Marvel Comics",
      alter_ego: "Scott Summers",
      first_appearance: "X-Men #1",
      characters: "Scott Summers",
      voto: 0,
      votoN: 0,
    },
    {
      idmovie: 18,
      nombre: "marvel_hawkeye",
      votos: 0,
      votosN: 0,
      superhero: "Hawkeye",
      publisher: "Marvel Comics",
      alter_ego: "Clinton Francis Barton",
      first_appearance: "Tales of Suspense #57",
      characters: "Clinton Francis Barton",
      voto: 0,
      votoN: 0,
    },
  ];
}
